### ISSUE TITLE
Want to Add Hover Effect to Home CTA Button

### ISSUE THREAD

**Issue by satyam73** [ishika1727/Stress-master#10]
Hello @ishika1727 I want to add hover effect to the home cta button.  

Please assign it to me under hacktoberfest label.

Thanks!

**Comment by ishika1727** [comment]
@satyam73 Please go ahead with the issue. I will assign the labels too.

**Comment by satyam73** [comment]
> @satyam73 Please go ahead with the issue. I will assign the labels too.

Thanks😄

**Comment by satyam73** [comment]
Hello @ishika1727 I have raised my PR #15 for this.
Please check it.
