### ISSUE TITLE
Change home background Image

### ISSUE THREAD

**Issue by ishika1727** [ishika1727/Stress-master#13]
Find a suitable background image for the home page and align it accordingly in `clone.css`

**Comment by kiran-thilak** [comment]
@ishika1727 Can i work on this?

**Comment by ishika1727** [comment]
@kiran-thilak please go ahead.

**Comment by MuhammadTanveer94** [comment]
@ishika1727 could you please assign me. i would love to work on this issue.

**Comment by kiran-thilak** [comment]
Hi @ishika1727 can we go for a stressed out person in the landing page? like this one : [a business woman who is stressed and frustrated](https://unsplash.com/photos/bmJAXAz6ads)

**Comment by satyam73** [comment]
> Hi @ishika1727 can we go for a stressed out person in the landing page? like this one : [a business woman who is stressed and frustrated](https://unsplash.com/photos/bmJAXAz6ads)

I think you should use some positive kind of image for landing page.

**Comment by kiran-thilak** [comment]
@satyam73 I think you are right. 
How about this a happy person with a gradient and some transparency:
![image](https://user-images.githubusercontent.com/8852764/135726687-d9cb0d1c-1c03-47b8-8fa0-7c5fbce14b08.png)

**Comment by kiran-thilak** [comment]
@ishika1727  and @satyam73  Please let me know the comments.

**Comment by satyam73** [comment]
> @satyam73 I think you are right. How about this a happy person with a gradient and some transparency: ![image](https://user-images.githubusercontent.com/8852764/135726687-d9cb0d1c-1c03-47b8-8fa0-7c5fbce14b08.png)

It's good
