### ISSUE TITLE
To modify form of diet section.

### ISSUE THREAD

**Issue by ankitbajpai65** [ishika1727/Stress-master#17]
Hello @ishika1727, I want to modify the form on the diet section and add placeholders for all input tags with some little changes.
Please assign it to me with the Hacktoberfest label.
Thanks!

**Comment by ishika1727** [comment]
@ankitbajpai65 please go ahead with the issue. Assigning it to you

**Comment by ankitbajpai65** [comment]
@ishika1727 I have raised PR #19. Please look into it.
Thanks!
