### ISSUE TITLE
Add hyperlink 

### ISSUE THREAD

**Issue by imobasshir** [ishika1727/Stress-master#64]
Add hyperlink to mail id and mobile in contact us section so it would be clickable.
If it is a genuine issue please assign it to me  under hacktober.

**Comment by sarthakahuja07** [comment]
Hi!! Can you assign this to me, I would love to work on this

**Comment by AnkitPatel1999** [comment]
I am working since last 1 year as frontend developer, can you please assign this issue to me. i make it the best as well as responsive
