### ISSUE TITLE
title of webpage 

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ishika1727/Stress-master#96]
title of page has html attribute
<font> tag is not supported in HTML 5 but used instead
![image](https://user-images.githubusercontent.com/72685413/137314864-eff32583-fc41-46c6-be9a-57d1cf5d90cb.png)

**Comment by itsPrajapat** [comment]
Could you please assign this issue to me

**Comment by ShouryaSrivastava01** [comment]
@ishika1727 i have resolved this error
